# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Site Settings
locale                   : "en-US"
title                    : "Trainingland Blog"
title_separator          : "|"
name                     : "Jessica Grosman"
description              : "Thoughts on making training"
url                      : "https://jessicagrosman.github.io"
baseurl                  : /blog
repository               : "jessicagrosman/blog"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
words_per_minute         : 200
comments:
  provider: "disqus"
  disqus: 
    shortname: "jgro"
# Site Author
author:
  name             : "Jessica Grosman"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : "I make training about tech."
  location         : "Montreal, Canada"
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Toronto
# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.14.2"
minimal_mistakes_skin: "default"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      related: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
